// 🐽 api 반영 후 제거
export const testConst = [
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
{
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },{
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
  {
    name: "권역명 001",
    count: "00",
    time: "소요시간",
    timeValue: "00시간 00분",
    distance: "운행거리",
    distanceValue: "000km",
    areaTime: "09:00",
    areaDistance: "00",
    area: "서울시 강남구 강남대로 476",
    workingHours: "00",
    travelTime: "00",
    memo: "메모 내용 입력 영역 입니다."
  },
];